spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    #      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties.hibernate.id.new_generator_mappings: false

  datasource:
    url: jdbc:mariadb://localhost:3306/restaurant
    username: root
    password: 666666
    driver-class-name: org.mariadb.jdbc.Driver

  output.ansi.enabled: always
  main.allow-bean-definition-overriding: true




server.port: 10001





